### ISSUE TITLE
User can view a list of items.

### ISSUE THREAD

**Issue by JordanTDawson** [JordanTDawson/dark-culture#1]
## 💰 Motivation

> ##### What capability will users have when this feature is merged?

User will be able to visit the homepage of my e-commerce website and view a basic list of items they can shop for. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will land on the homepage and will be able to see the carousel of different items they can view the items on the homepage. A functional carousel will be showing different images of items that are for sale. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="283" alt="Screen Shot 2023-02-24 at 10 13 19 AM" src="https://user-images.githubusercontent.com/117692796/221257480-18aa9844-4c28-4b6e-88b5-27fc290e680e.png">
<img width="406" alt="Screen Shot 2023-02-24 at 10 13 48 AM" src="https://user-images.githubusercontent.com/117692796/221257548-6b8c34da-7fcf-4f06-a661-e09109ec09b1.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to import the database created from the schema website. 
- [x] Update `data.sql` to insert all data required for the catalog.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a GET request to the sql database with all hardcoded info.
- [x] Test with HTTPie to make sure requests are sending through.
- [x] Handle all errors and respond to the client.

### ⚡ Client Tasks

- [x] Create a nav bar component.
    - [x] Create Hash Routing between pages.
- [x] Create a hero image component.
- [x] Create a 3 column advertisement of products.
- [x] Create a carousel component that shows different featured items for purchase.
- [x] Create a footer that advertises the brands that are showcase for the website.
- [x] Create a footer that has buttons for rerouting to other pages.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
